// The Codex agent files are generated from the kind table: one per agent entry
// and one per low twin, with the codex block's model and effort, a sandbox that
// approximates the tool list, and the preamble ahead of the agent body.

import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { test } from 'node:test';
import { findAgentDrift, generateAgents } from '../harnesses/codex/write-agents.mjs';

const ROOT = new URL('../', import.meta.url).pathname;
const agentFiles = fs.readdirSync(path.join(ROOT, 'agents')).filter((name) => name.endsWith('.md'));

function field(text, name) {
  const line = text.split('\n').find((row) => row.startsWith(`${name} = `));
  return line === undefined ? null : JSON.parse(line.slice(name.length + 3));
}

function generated(name) {
  return generateAgents(ROOT).get(path.join('harnesses', 'codex', 'agents', `${name}.toml`));
}

function copyOfRepository() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'codex-agents-'));
  for (const entry of ['agents', 'lib', 'harnesses']) fs.cpSync(path.join(ROOT, entry), path.join(root, entry), { recursive: true });
  return root;
}

test('one file per agent entry plus the two low twins, and no other', () => {
  const names = [...generateAgents(ROOT).keys()].map((file) => path.basename(file, '.toml')).sort();
  const expected = [
    ...agentFiles.map((name) => `exo-${path.basename(name, '.md')}`),
    'exo-critique-ui-low',
    'exo-review-branch-deep-low'
  ].sort();
  assert.equal(names.length, 17);
  assert.deepEqual(names, expected);
});

test('each file holds the decided fields and drops maxTurns and omitClaudeMd', () => {
  for (const text of generateAgents(ROOT).values()) {
    assert.ok(field(text, 'name').startsWith('exo-'));
    assert.ok(field(text, 'description').length > 0);
    assert.ok(field(text, 'model'));
    assert.ok(field(text, 'model_reasoning_effort'));
    assert.ok(['read-only', 'workspace-write'].includes(field(text, 'sandbox_mode')));
    assert.match(text, /\ndeveloper_instructions = '''\n/);
    assert.doesNotMatch(text, /^\s*(maxTurns|omitClaudeMd)\s*[:=]/m);
  }
});

test('model and effort resolve through the codex block, shifted up one step on the strong tier', () => {
  const build = generated('exo-build-task');
  assert.equal(field(build, 'model'), 'gpt-6.1-sol');
  assert.equal(field(build, 'model_reasoning_effort'), 'high');
  const critique = generated('exo-critique-ui');
  assert.equal(field(critique, 'model'), 'gpt-6.1-sol');
  assert.equal(field(critique, 'model_reasoning_effort'), 'xhigh');
  const lookup = generated('exo-locate-code');
  assert.equal(field(lookup, 'model'), 'gpt-6-luna');
  assert.equal(field(lookup, 'model_reasoning_effort'), 'medium');
});

test('a low twin takes the low budget tier and keeps its source body', () => {
  const twin = generated('exo-critique-ui-low');
  assert.equal(field(twin, 'name'), 'exo-critique-ui-low');
  assert.equal(field(twin, 'model'), 'gpt-6.1-sol');
  assert.equal(field(twin, 'model_reasoning_effort'), 'high');
  const body = fs.readFileSync(path.join(ROOT, 'agents', 'critique-ui.md'), 'utf8').split('\n---\n')[1].trim();
  assert.ok(twin.includes(body));
  assert.ok(generated('exo-review-branch-deep-low').includes('exo-review-branch-deep-low'));
});

test('only the agents without Edit or Write run read-only', () => {
  const readOnly = [...generateAgents(ROOT).entries()]
    .filter(([, text]) => field(text, 'sandbox_mode') === 'read-only')
    .map(([file]) => path.basename(file, '.toml'))
    .sort();
  assert.deepEqual(readOnly, ['exo-fetch-docs', 'exo-locate-code']);
});

test('the instructions open with the preamble and then the agent body', () => {
  const preamble = fs.readFileSync(path.join(ROOT, 'harnesses', 'codex', 'agent-preamble.md'), 'utf8');
  const text = generated('exo-locate-code');
  assert.ok(text.includes(`'''\n${preamble.trimEnd()}\n\n`));
  assert.ok(text.includes('You are a read-only codebase explorer.'));
  assert.ok(!text.includes('tools: Read'));
});

test('the committed files match the table', () => {
  assert.deepEqual(findAgentDrift(ROOT), []);
});

test('--check exits 1 and names a changed, a missing and a stray file', () => {
  const root = copyOfRepository();
  const directory = path.join(root, 'harnesses', 'codex', 'agents');
  fs.appendFileSync(path.join(directory, 'exo-build-task.toml'), '# drift\n');
  fs.rmSync(path.join(directory, 'exo-locate-code.toml'));
  fs.writeFileSync(path.join(directory, 'exo-stray.toml'), 'name = "exo-stray"\n');
  const drift = findAgentDrift(root).map((record) => `${path.basename(record.file)}: ${record.problem}`).sort();
  assert.deepEqual(drift, [
    'exo-build-task.toml: differs from the table',
    'exo-locate-code.toml: missing',
    'exo-stray.toml: not generated by the table'
  ]);
  const result = spawnSync('node', [path.join(root, 'harnesses', 'codex', 'write-agents.mjs'), '--check'], { encoding: 'utf8' });
  assert.equal(result.status, 1);
  assert.match(result.stdout, /exo-build-task\.toml: differs from the table/);
});
