// The commit-text checks refuse AI attribution in commit and pull-request text,
// a non-Conventional subject, and a branch named for an AI, while text that names
// the product as its subject passes.

import assert from 'node:assert/strict';
import { test } from 'node:test';
import { attributionProblem, branchNameProblem, subjectProblem } from '../lib/commit-text.mjs';

test('attribution phrases are refused wherever they land', () => {
  for (const text of [
    'feat: add x\n\nCo-Authored-By: Claude <noreply@anthropic.com>',
    'Generated with Claude Code',
    'feat: add x robot_face',
    'Co-authored: <noreply@anthropic.com>',
    'Generated by Claude',
    'generated   with a tool',
    'Made with Claude Code',
    'Written by [Claude Code](https://claude.com/claude-code)',
    'see https://claude.com/claude-code'
  ]) {
    assert.match(attributionProblem(text), /must not attribute the work to an AI/, text);
  }
});

test('attribution in the trailers of a commit message is refused', () => {
  const message = (trailer) => `fix(parser): repair the loop\n\nWhy it changed.\n\nPlan-task: 3\n${trailer}`;
  assert.equal(attributionProblem(message('Reviewed-by: a person')), null);
  for (const trailer of ['Co-Authored-By: Claude', 'Generated with Claude Code', 'Co-authored: <noreply@anthropic.com>']) {
    assert.match(attributionProblem(message(trailer)), /must not attribute/, trailer);
  }
});

test('text that names Claude Code as its subject passes', () => {
  assert.equal(attributionProblem('The Usage view is empty on Claude Code 2.1.289.'), null);
  assert.equal(attributionProblem("Claude Code's auto memory is unaffected."), null);
  assert.equal(attributionProblem('fix(hooks): repair the view\n\nClaude Code 2.1.289 leaves it empty.'), null);
  assert.equal(attributionProblem('chore(claude): bump the plugin manifest'), null);
  assert.equal(attributionProblem('Repairs the loop'), null);
});

test('a conventional subject passes and one without a type is refused with the types named', () => {
  for (const subject of ['feat(hooks): add the commit check', 'fix!: drop the flag', 'docs: explain', 'chore(claude): bump']) {
    assert.equal(subjectProblem(subject), null, subject);
  }
  for (const subject of ['add the commit check', 'Feat: add', 'feat:add', 'wip', '']) {
    assert.match(subjectProblem(subject), /Conventional Commits.*build, chore, ci, docs, feat/, subject);
  }
});

test('a branch named for an AI is refused', () => {
  for (const name of [
    'claude/fix-login',
    'codex/topic',
    'copilot/topic',
    'fix/co-authored-by-bot',
    'fix/claude-code-run',
    'fix/claude-code-thing',
    'fix/claude/code-thing',
    'fix/claude_code-run',
    'fix/generated-by-tool',
    'fix/noreply@anthropic.com'
  ]) {
    assert.match(branchNameProblem(name), /branch name must not name an AI/, name);
  }
});

test('a branch named for the change passes, and so does one that only has claude in a scope', () => {
  for (const name of ['fix/login-redirect', 'feat/claude-scope', 'main', 'chore/claude']) {
    assert.equal(branchNameProblem(name), null, name);
  }
});
