// Generates one Codex custom-agent file per `agents/*.md` entry of the kind
// table, plus one per `providers.codex.lowTwins` entry, into `harnesses/codex/agents/`.
// Model and reasoning effort come from the table's codex block; the body is
// `harnesses/codex/agent-preamble.md` followed by the agent's own body.
//
//   node harnesses/codex/write-agents.mjs           write the files
//   node harnesses/codex/write-agents.mjs --check   list drift and exit 1 when any
//
// The sandbox approximates the tool allowlist: `read-only` for the agents in
// READ_ONLY, whose tools hold no Edit or Write, `workspace-write` for the rest
// (run-unit has neither tool but lands commits through Bash, so it writes).
// `maxTurns` and `omitClaudeMd` have no Codex field and are dropped.

import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { INHERIT, readKindTable } from '../../lib/model-kinds.mjs';

const ROOT = fileURLToPath(new URL('../..', import.meta.url));
const READ_ONLY = ['agents/fetch-docs.md', 'agents/locate-code.md'];
const FRONTMATTER = /^---\n([\s\S]*?)\n---\n/;

function readField(frontmatter, field) {
  const line = frontmatter.split('\n').find((row) => row.startsWith(`${field}:`));
  if (line === undefined) return null;
  const value = line.slice(field.length + 1).trim();
  return value.startsWith('"') ? JSON.parse(value) : value;
}

// A JSON string is a valid TOML basic string.
function tomlString(text) {
  return JSON.stringify(text);
}

// The multi-line literal string takes the text verbatim, so no escape can
// alter an instruction; its one limit is a body holding three single quotes.
function tomlLiteralBlock(text) {
  if (text.includes("'''")) {
    throw new Error("an agent body holds ''', which a TOML literal string cannot carry; reword it");
  }
  return `'''\n${text}'''`;
}

function renderAgent({ name, description, instructions, model, effort, sandbox }) {
  const lines = [
    `name = ${tomlString(name)}`,
    `description = ${tomlString(description)}`
  ];
  if (model !== INHERIT) lines.push(`model = ${tomlString(model)}`);
  if (effort !== null) lines.push(`model_reasoning_effort = ${tomlString(effort)}`);
  lines.push(`sandbox_mode = ${tomlString(sandbox)}`);
  lines.push(`developer_instructions = ${tomlLiteralBlock(instructions)}`);
  return `${lines.join('\n')}\n`;
}

// Returns a Map of path relative to `root` to the file's expected text.
export function generateAgents(root = ROOT) {
  const table = readKindTable(path.join(root, 'lib', 'model-kinds.json'), { provider: 'codex' });
  const preamble = fs.readFileSync(path.join(root, 'harnesses', 'codex', 'agent-preamble.md'), 'utf8');
  const files = new Map();

  function add(name, file, entry, resolved, description) {
    const text = fs.readFileSync(path.join(root, entry.generatedFrom ?? file), 'utf8');
    const [opening] = FRONTMATTER.exec(text);
    const own = FRONTMATTER.exec(fs.readFileSync(path.join(root, file), 'utf8'))[1];
    files.set(path.join('harnesses', 'codex', 'agents', `${name}.toml`), renderAgent({
      name,
      description: description ?? entry.description ?? readField(own, 'description'),
      instructions: `${preamble.trimEnd()}\n\n${text.slice(opening.length).replace(/^\n+/, '')}`,
      model: resolved.model,
      effort: resolved.effort,
      sandbox: READ_ONLY.includes(file) ? 'read-only' : 'workspace-write'
    }));
  }

  for (const [file, entry] of Object.entries(table.agents)) {
    add(`exo-${path.basename(file, '.md')}`, file, entry, table.kinds[entry.kind]);
  }
  for (const [file, twin] of Object.entries(table.lowTwins)) {
    const source = path.basename(file, '.md');
    const description = `${source} at ${twin.model} and ${twin.effort} effort for the low budget, dispatched by name only.`;
    add(twin.name, file, table.agents[file], twin, description);
  }
  return files;
}

// Lists drift as { file, problem } records, empty when every file matches and
// no stray `.toml` sits in `harnesses/codex/agents/`.
export function findAgentDrift(root = ROOT) {
  const expected = generateAgents(root);
  const drift = [];
  for (const [file, text] of expected) {
    const location = path.join(root, file);
    if (!fs.existsSync(location)) drift.push({ file, problem: 'missing' });
    else if (fs.readFileSync(location, 'utf8') !== text) drift.push({ file, problem: 'differs from the table' });
  }
  const directory = path.join(root, 'harnesses', 'codex', 'agents');
  const present = fs.existsSync(directory) ? fs.readdirSync(directory).filter((name) => name.endsWith('.toml')) : [];
  for (const name of present) {
    const file = path.join('harnesses', 'codex', 'agents', name);
    if (!expected.has(file)) drift.push({ file, problem: 'not generated by the table' });
  }
  return drift;
}

// A stray file stays: `--check` names it, and the user decides whether to delete it.
export function writeAgents(root = ROOT) {
  fs.mkdirSync(path.join(root, 'harnesses', 'codex', 'agents'), { recursive: true });
  for (const [file, text] of generateAgents(root)) fs.writeFileSync(path.join(root, file), text);
}

function main() {
  const { values } = parseArgs({ options: { check: { type: 'boolean', default: false } } });
  if (!values.check) {
    writeAgents();
    return;
  }
  const drift = findAgentDrift();
  for (const record of drift) console.log(`${record.file}: ${record.problem}`);
  if (drift.length > 0) process.exitCode = 1;
}

if (fs.realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) main();
